### ISSUE TITLE
wg-performance Quarterly Status Update 2019-09

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/wg-performance#18]
## AMP Script
- WorkerDOM has been released [7 times](https://github.com/ampproject/worker-dom/releases) this quarter so far.
- AMP Script was made generally available to all AMP documents.
- New Features: Local Storage / Session Storage, WebSockets, Global Event Subscriptions, Passing / Setting AMP State between threads.
- Performance Improvements for frequently used DOM Operations
 
## AMP Service Worker
- Forced Nullification (forcing an existing ServiceWorker to be replaced with a nullified one) shipped.
- Work slowed due to slow adoption and staffing limitations.

## AMP Performance Analysis Tool
- Tool complete and is usable by AMP Contributors to see the impact of their changes in synthetic environments. 

## AMP Performance
- Exiting micro-task loop (to macro-task) when a task exceeds a time threshold has shipped as a URL level opt-in, showing promising results on documents in production.
- Error Message Extraction (from strings to numerical identifiers) is near completion. This will provide a binary size reduction and a DX improvement since errors will link to `amp.dev` with additional context.
- Preload logic moved from `HTMLLabelElement`s to `Link` Response Headers (2% faster install styles metric).
- Layers API Removed (2.5kb reduction)
- New Custom Elements v1 Polyfill removing older v0 Polyfill (4kb reduction)

**Comment by jridgewell** [comment]
Launched `<link ref=preload>` extraction into `Link` Response Headers (2% faster Install Styles metric)

**Comment by jridgewell** [comment]
Layers code removed (2.5kb)

**Comment by jridgewell** [comment]
Custom elements v1 polyfill in Canary (will save 4kb once we remove v0 polyfill)
