### ISSUE TITLE
Pixi: Poor page experience

### ISSUE THREAD

**Issue by barruka** [ampproject/wg-performance#52]
URL
---
https://www.alpel.es/hoja-cuchilla-afeitar-ragnar-100-unid-simple

Details
---

| Metric                 | Field data | Lab data |
|-----------------|------------|---------|
| LCP | n/a | 3.8 s |
| FID  | n/a | 118 ms |
| CLS  | n/a | 0.26  |
| HTTPS  | pass | --- |
| Safe browsing  | pass | --- |
| Mobile-friendliness  | pass | --- |
| Intrusive Interstitials | <pass/fail> | --- |

Notes
---

Components in use: amp-analytics, amp-sidebar, amp-form, amp-image-lightbox

/cc @ampproject/wg-performance

**Comment by kristoferbaxter** [comment]
Thanks for the report, I've added Kevin Kimball to the issue to take a look.

**Comment by kristoferbaxter** [comment]
Also, it spreads there are 3 recommendations for this example.

![image](https://user-images.githubusercontent.com/61764/96373904-3cb63100-1124-11eb-847a-29e331627f76.jpeg)

Can we address these three and re-run?

**Comment by barruka** [comment]
@kristoferbaxter I am very sorry but I really think that the issue is not with that three recomendations, let me explain myself:

First: Got the page and saved it like .html:
https://www.alpel.es/test_amp.html

Secong: Edit .html and remove all amp js and style boilerplate, changed amp-img to img and saved it:
https://www.alpel.es/test_noamp.html

I tried to keep html as equal as possible in both pages, so I didn't remove on="tap:AMP.navigateTo

Theese three recomendations are even on both html files, same images and same initial server response time.

I don't know if these files can provide any help to you, sorry for not being able to help you.

**Comment by kristoferbaxter** [comment]
Assigning this back to me. I'll create a public copy of this document with the AMP Optimizer, transformed hero images, and a shorter response time from the server as an example.

**Comment by kristoferbaxter** [comment]
@barruka I created a temporary copy of the origin document and applied a few of the recommendations from the Page Experience tool (Pixi).

**Before**
<img width="1035" alt="Screen Shot 2020-10-19 at 11 47 01 AM" src="https://user-images.githubusercontent.com/61764/96498404-de12b500-1200-11eb-9249-0bdb809a584c.png">

**After**
<img width="1031" alt="Screen Shot 2020-10-19 at 11 44 17 AM" src="https://user-images.githubusercontent.com/61764/96498188-99871980-1200-11eb-826a-60f5d9728618.png">

With some of the recommendations applied from the tool, the following changes occured:
| Category | Before | After |
| --- | --- | --- |
| LCP | 3.5s | **2.8s** |
| TBT | 120ms | **136ms** |
| CLS | 0.21 | **0.09** | 

This means the only category in the lab data tests needing enhancement is LCP.

Using the final recommendation from Pixi "Use the JavaScript Module version of the AMP Runtime", is currently experimental and results in an invalid AMP Page. However, I was able to force the results and this moved LCP to **2.6s**. @nainar is working with the Caching Working group to ensure this incongruity is addressed quickly.

This means the result from all the recommendations is a page that is passing and not passing Core Web Vitals based on network conditions within the Lab environment. In our experience, this means the document will pass in the real world based on the 75th percentile of real world traffic.

**Comment by barruka** [comment]
@kristoferbaxter what a great job, thank you very much!
I'm sure everyone really appreciates your effort

**Comment by kristoferbaxter** [comment]
Closing this issue out. Seems resolved.
