### ISSUE TITLE
Page Experience with URL parameter doesn't autosubmit test

### ISSUE THREAD

**Issue by gilbertococchi** [ampproject/wg-performance#54]
Hi all, Pixi URL with query parameter https://amp.dev/page-experience/?url=https://www.dailymail.co.uk/news/article-8850761/amp/Londons-normally-bustling-streets-bars-deserted-day-one-new-Tier-2-lockdown.html seems not to automatically trigger the "Analyze" on navigation if link is saved.

I believe it would idea to consider to automatically submit the test when clicking on a Pixi link already including a test URL.

/cc @ampproject/wg-performance

**Comment by nainar** [comment]
This is WAI - we can't do this with <amp-script> currently. needs user interaction.

**Comment by nainar** [comment]
cc @kevinkimball to close
