### ISSUE TITLE
wg-performance Status Update 2021-06-07

### ISSUE THREAD

**Issue by jridgewell** [ampproject/wg-performance#84]
cc @ampproject/wg-performance

**Comment by samouri** [comment]
## What was accomplished
- Explored Maui. 
  - [x] Road to Hana. 
  - [x] Surfing in Lahaina 
- Explored Kauai.
  - [x] kalaluu trail
  - [x] Waimea Canyon
- Big Island
  - [x] Walk on volcano 
  - [x] See the Milky Way 

## Lessons Learned

Taking a break is A+

## What's Next

- server rendering amp components

**Comment by jridgewell** [comment]
## What was accomplished
- SSR fluid layout: cl/375756231
- Better optimize WebP image generation during ingestion: cl/375986686
- Ingestion only branch for image experiment: cl/377110349
- New experiment framework for faster SSR experiments: cl/376059362, cl/377108647
- Compress hot-patched amp-geo with brotli (finally!): cl/377307679

## Lessons Learned
- Our CSI metrics are sometimes incorrect, because aggregating a percentile is incorrect.

## What's Next
- Fix CSI metrics
- Prototype Jolt

**Comment by erwinmombay** [comment]
## What was accomplished
- tested new chrome experimental flags and they're interaction with LCP, CLS, font loading 
- results from AVIF/WebP experiments

## Lessons Learned

## What's Next
- prioritize render time over load time on LCP reporting
- add Timing-Allow-Origin

**Comment by rcebulko** [comment]
## What was accomplished
- Aliased import paths https://github.com/ampproject/amphtml/pull/34562
- lots of core migration and type-checking
- path forward on compiler security sandboxing

## What's Next
- compiler security sandboxing
- finish core extraction
- Type-check `src/preact` so Bento components can be type-checked

**Comment by trademinister** [comment]
Hello,
Created AMP page for Shopify platform - https://trademinister.net/
Can You recommend how can I boost PageSpeed score above 90?
Attached current web.dev/measure status
![trademinister-webdev-measure2](https://user-images.githubusercontent.com/23034301/121695170-7a146800-cad3-11eb-9479-479ad6ad4d13.png)

**Comment by rcebulko** [comment]
It's interesting that Lighthouse is seeing FCP at 3.5s (confirmed locally) even though the Performance tab of DevTools shows it at ~680ms:

![image](https://user-images.githubusercontent.com/6694512/121709246-5981e900-caa6-11eb-9243-bb6977c00396.png)

As an aside, it looks like the page JS fetches amp-auto-lightbox via JS, rather than it being included in the page at load time. I don't think that should be the issue, though. This isn't the right thread for a deep discussion; could you either file a separate issue or post under the `#using-amp` channel on the AMP Slack?

**Comment by samouri** [comment]
@rcebulko: are you using the same [throttling settings](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md#the-mobile-network-throttling-preset) as lighthouse?

**Comment by trademinister** [comment]
Hello Ryan,

Can You tell me how to subscribe to AMP Slack channel?

пт, 11 июн. 2021 г., 18:17 Ryan Cebulko ***@***.***>:

**Comment by rcebulko** [comment]
@trademinister see https://github.com/ampproject/amphtml/blob/main/docs/contributing.md#discussion-channels

**Comment by trademinister** [comment]
Hello Ryan,

Thanks for the help

пт, 11 июн. 2021 г., 23:10 Ryan Cebulko ***@***.***>:
